import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: "Communities", href: "/community" },
  { name: "Discussions", href: "/discussion" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = {
    fullName: "John Doe",
  };
  return (
    <html lang="en">
      <body
        className={`flex flex-col ${geistSans.variable} ${geistMono.variable}`}
      >
        <header className="bg-blue-600">
          <div className="w-full flex flex-row justify-between px-4">
            <div className="lg:w-1/2 flex flex-col lg:flex-row gap-8 items-center py-4">
              <Link className="font-bold text-xl text-gray-100" href={"/"}>
                NextTribe
              </Link>
            </div>
            <div className="lg:w-1/2 flex flex-row p-4 lg:p-0 gap-8 items-center justify-center lg:justify-end">
              {user ? (
                <>
                  {navigation.map((item) => (
                    <Link
                      key={item.name}
                      href={item.href}
                      className="text-sm/6 font-medium text-gray-100"
                    >
                      {item.name}
                    </Link>
                  ))}
                </>
              ) : (
                <>
                  <Link href="/sign-in" className={"text-gray-300"}>
                    Sign In
                  </Link>
                  <Link href="/sign-up" className={"text-gray-300"}>
                    Join Now
                  </Link>
                </>
              )}
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
