import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: "Sign In", href: "/sign-in" },
  { name: "Sign Up", href: "/sign-up" },
];

async function getUserFromCookie() {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get("token")?.value;
    if (!token) return null;
    const secret = process.env.JWT_SECRET;
    if (!secret) return null;
    const key = new TextEncoder().encode(secret);
    const { payload } = await jwtVerify(token, key);
    return {
      id: typeof payload.sub === "string" ? payload.sub : undefined,
      email: typeof payload.email === "string" ? payload.email : undefined,
      name: typeof payload.name === "string" ? payload.name : undefined,
    } as { id?: string; email?: string; name?: string };
  } catch {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie();
  return (
    <html lang="en">
      <body
        className={`flex flex-col ${geistSans.variable} ${geistMono.variable}`}
      >
        <header className="bg-blue-600 h-16">
          <div className="w-full flex flex-row justify-between px-4">
            <div className="lg:w-1/2 flex flex-col lg:flex-row gap-8 items-center py-4">
              <Link className="font-bold text-xl text-gray-100" href={"/"}>
                NextTribe
              </Link>
            </div>
            <div className="lg:w-1/2 flex flex-row p-4 lg:p-0 gap-8 items-center justify-center lg:justify-end">
              {user && user.name ? (
                <div className="flex items-center gap-4">
                  <div className="text-gray-100 text-sm font-medium">Hi, {user.name}</div>
                  <form action="/api/auth/logout" method="post">
                    <button
                      type="submit"
                      className="text-sm/6 font-medium text-gray-100 hover:underline"
                    >
                      Log out
                    </button>
                  </form>
                </div>
              ) : (
                <>
                  {navigation.map((item) => (
                    <Link
                      key={item.name}
                      href={item.href}
                      className="text-sm/6 font-medium text-gray-100"
                    >
                      {item.name}
                    </Link>
                  ))}
                </>
              )}
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}

