import type { Metadata } from "next";
import Link from "next/link";
import {
  HomeIcon,
  CompassIcon,
  MessageSquareIcon,
  SettingsIcon,
  LinkIcon,
} from "lucide-react";
import MyCommunities from "@/components/layout/MyCommunities";

export const metadata: Metadata = {
  title: "Nextribe | Home",
  description: "Generated by create next app",
};

// Left sidebar data
const importantLinks = [
  { href: "/", label: "Home", icon: HomeIcon },
  { href: "/community", label: "Explore", icon: CompassIcon },
  { href: "/discussion", label: "Discussions", icon: MessageSquareIcon },
  { href: "/settings", label: "Settings", icon: SettingsIcon },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <main className="w-full flex-1 overflow-y-auto p-4">
      <div className="w-full flex flex-col lg:flex-row gap-4 max-w-7xl mx-auto">
        {/* Left sidebar */}
        <aside className="flex flex-col lg:w-1/5 gap-4">

          <div className="bg-white border border-gray-200 rounded-xl p-3">
            <h3 className="text-sm font-semibold mb-2 inline-flex items-center gap-2">
              <LinkIcon className="w-4 h-4" /> Important
            </h3>
            <nav className="flex flex-col gap-1">
              {importantLinks.map(({ href, label, icon: Icon }) => (
                <Link
                  key={label}
                  href={href}
                  className="flex items-center gap-2 rounded-lg px-2 py-2 hover:bg-gray-50 text-sm text-slate-700"
                >
                  <Icon className="w-4 h-4" />
                  <span>{label}</span>
                </Link>
              ))}
            </nav>
          </div>

          <MyCommunities />
        </aside>
        {children}
      </div>
    </main>
  );
}
