import type { Metadata } from "next";
import { getUserFromCookie } from "@/lib/auth";
import LeftSideBar from "@/components/layout/LeftSideBar";
import { PopularCommunities } from "@/components/community/PopularCommunities";
import { TopDiscussions } from "@/components/discussions/TopDiscussions";

export const metadata: Metadata = {
  title: "Nextribe | Home",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie();

  return (
    <main className="w-full flex-1 overflow-y-auto p-4">
      <div className="w-full flex flex-col lg:flex-row gap-4 max-w-7xl mx-auto">
        <LeftSideBar user={user!} />
        {children}

      {/* Right sidebar */}
      <aside className="flex flex-col lg:w-1/5 gap-4">
        <PopularCommunities />
        <TopDiscussions />
      </aside>
      </div>
    </main>
  );
}
